env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  LocalFile {
    tables_configs = [
      {
        schema {
          table = "_sgcc_aa22aaaagybphwp3w"
        }
        path = "/data/output/_sgcc_aa22aaaagybphwp3w"
        file_format_type = "parquet"
      }
      {
        schema {
          table = "_sgcc_acs4aaaag2g3ud6d2"
        }
        path = "/data/output/_sgcc_acs4aaaag2g3ud6d2"
        file_format_type = "parquet"
      }
    ]
  }
}

sink {
  Milvus {
    url = "http://192.162.11.52:29530"
    token = "root:Milvus"
    database = "bak2"
    schema_save_mode = "CREATE_SCHEMA_WHEN_NOT_EXIST"
    batch_size = 100
  }
}
