env {
  parallelism = 1
}

source {
  Milvus {
    url = "http://192.162.11.52:29530"
    token = "root:Milvus"
    database = "default"
    collections = ["_sgcc_acs4aaaag2g3ud6d2"]
    batch_size = 100
  }
}

sink {
  LocalFile {
    path = "/data/output/_sgcc_acs4aaaag2g3ud6d2"
    file_format_type = "parquet"
  }
}
