env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  Milvus {
    url = "http://192.162.11.10:29530"
    token = "root:Milvus"
    database = "default"
    collections = [
      "_sgcc_acs4aaaag2g3ud6d2"
      "_sgcc_aa22aaaagybphwp3w"
    ]
    batch_size = 100
  }
}

sink {
  LocalFile {
    # Use source metadata table_name (Milvus collection name) to split output folders.
    path = "/data/output/${table_name}"
    file_format_type = "parquet"
  }
}
