env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  Milvus {
    url = "http://192.162.11.52:29530"
    token = "root:Milvus"
    database = "default"
    collections = [
      "_txa_1_aaaaatkw7426m"
      "_txa_aag6aaaagcdatq5js"
      "_sgcc_aaxgaaaagcovrux7q"
      "_sgcc_adb4aaaaglm37abck"
      "_sgcc_abaeaaaagyfqidhly"
      "_txa_aabsaaaaggc5cs674"
      "_sgcc_adlyaaaagclubbs3a"
      "_sgcc_abtuaaaagzstrq224"
      "default_20535"
      "_temporary_data_11_abfgaaaahbgdt2tws"
      "_11_ablwaaaag6emk3esq"
      "hello"
      "_sgcc_abo6aaaagb3lx5j6k"
      "_sgcc_afi6aaaagb3jw5uhe"
      "_11_abtqaaaage6scb3kq"
      "_sgcc_aa22aaaagybphwp3w"
      "_sgcc_aasgaaaagzsskuxzw"
      "_sgcc_2_aaaaask4blkme"
      "_sgcc_6f873e96db1111f0"
      "default_20525"
      "_temporary_data_11_apxiaaaag5uhthqmw"
      "default_20539"
      "default_20543"
      "_sgcc_aasqaaaagf3uhpx36"
      "default_20521"
      "_temporary_data_11_akhoaaaag5ubaelty"
      "_temporary_data_11_aegkaaaag5uq32ftk"
      "_sgcc_acdwaaaagb3knpzsy"
      "_sgcc_8_aaaaasdfdt3ec"
      "_sgcc_aarqaaaagb3tzxw46"
      "_sgcc_70_aaaaasudeb3xo"
      "_sgcc_ab2uaaaagzsq5ixw2"
      "default_20522"
      "default_20532"
      "_temporary_data_txa_aaw6aaaagbthxu2pi"
      "_sgcc_049a74f2be0d11f0"
      "default_20476"
      "_sgcc_abkaaaaagfpalmfka"
      "default_20523"
      "_sgcc_dnzkaaaageosgtfua"
      "_sgcc_acs4aaaag2g3ud6d2"
      "default_20475"
      "_sgcc_aavcaaaaga7i7qjxo"
      "default_20474"
      "_txa_aaaiaaaaggb6r7giq"
      "_txa_aafmaaaaggchgynzi"
      "memoryDB"
      "_txa_aafqaaaaggb4akw34"
      "_sgcc_aal6aaaagzu2tqhya"
      "_sgcc_aaxeaaaagbrwn53as"
      "_txa_aacwaaaagccyrw3vo"
      "default_20536"
      "_temporary_data_11_aazcaaaahbghuok2m"
      "default_20538"
      "_sgcc_adziaaaagbog5bboq"
      "qw_kg_base"
      "_sgcc_ab6yaaaagzsrjdr6i"
      "_temporary_data_11_aevoaaaag5umxty66"
      "_sgcc_acrmaaaagb6kyi6l6"
      "default_20510"
      "default_20515"
      "_sgcc_acnqaaaahbtpqxti4"
      "default_20537"
      "_sgcc_aa2uaaaagckglorna"
      "_sgcc_ab54aaaagyfypohzu"
      "default_20528"
      "_temporary_data_11_aessaaaag5t7kjtgy"
      "_temporary_data_11_abd6aaaahbgfskino"
      "_txa_aafoaaaagb6nzi5ik"
      "_txa_aapyaaaagf74gjkji"
      "_txa_aabyaaaaggcxcphoc"
      "_sgcc_abryaaaagsv5qg3io"
      "default_20511"
      "default_20514"
      "default_20518"
      "default_20473"
      "_txa_aacuaaaaggcjidp2e"
      "default_20516"
      "default_20517"
      "_sgcc_aawkaaaag2szxqdiq"
      "_sgcc_aaeyaaaagb6pghddm"
      "_zhujie_1_aaaaaszksjuwc"
      "_txa_aaoqaaaaggaexnqua"
      "_txa_aafqaaaaggbxino4o"
      "default_20530"
      "default_20531"
      "_11_abcoaaaag3u35poyq"
      "_sgcc_aasgaaaagcdm6gdfq"
      "default_20472"
      "_sgcc_aaxmaaaagbkoijojk"
    ]
    batch_size = 100
  }
}

sink {
  LocalFile {
    path = "/data/output/${table_name}"
    file_format_type = "parquet"
  }
}
